application: khan-webhooks
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: markupsafe
  version: "0.15"
- name: jinja2
  version: "2.6"

handlers:
- url: .*
  script : main.app
